---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Etc/UTC
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:10"
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:20"
      timezone: Etc/UTC
    groups:
      container-images:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: /.devcontainer
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Etc/UTC
    groups:
      devcontainer-features:
        patterns:
          - "*"
