# syntax=docker/dockerfile:1.7

ARG JEKYLL_BUILD_PAGES_VERSION=v1.0.13
FROM ghcr.io/actions/jekyll-build-pages:${JEKYLL_BUILD_PAGES_VERSION}@sha256:6791ebfd912185ed59bfb5fb102664fa872496b79f87ff8b9cfba292a7345041

COPY . /github/workspace
WORKDIR /github/workspace

ENV INPUT_SOURCE=./site-build \
    INPUT_DESTINATION=./_site \
    INPUT_FUTURE=false \
    INPUT_VERBOSE=false \
    INPUT_TOKEN= \
    GITHUB_WORKSPACE=/github/workspace

RUN /entrypoint.sh
