# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobman" do
  version "0.8.3"

  on_macos do
    on_intel do
      sha256 "34955c4abc541a1194dd6797cb9ad39b79bf0b0ee175614b13c08a87ad8661ac"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a8ccc9798734f4e94f56864126da8247b6b2e62f0ec80d7f130ea8219a4ed4b"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "983949ce95fc30629f948091292f6d1f0033b8b8cbf69cedf1902ac0952cea3b"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "238f29bf959a23e289dc1c28fd2cc465547753aa8d272cdf207ae226598391ca"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jobman"
  desc "A daemon-less command line job manager with retries, timeouts, logging, notifications, and more."
  homepage "https://github.com/ryancswallace/jobman"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobman"
  manpage "docs/manpage/jobman.1"
  bash_completion "docs/completions/bash/jobman"
  zsh_completion "docs/completions/zsh/_jobman"

  # No zap stanza required

end
