# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobman" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "38afed049f86f58c10185472766778298415ede653165788b1c6afcb108351d5"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6dfbd85b26c998e61b50cdc8f32ade3a83228f22ffe416d1a48ba4a4ab4658f9"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2b801882edf2f917132ed5028058bc9b15f1b709cc992991994ff787757a21d"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d295c101c1a425426b692b77e902172c27b99b04586bbb67a59d94d5d8fd967"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jobman"
  desc "A daemon-less command line job manager with retries, timeouts, logging, notifications, and more."
  homepage "https://github.com/ryancswallace/jobman"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobman"
  manpage "docs/manpage/jobman.1"
  bash_completion "docs/completions/bash/jobman"
  zsh_completion "docs/completions/zsh/_jobman"

  # No zap stanza required

end
