# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobman" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "7218faf16cc72833f27c8a14a8810b15d735c4049e7b28582152c64a226b1dbb"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "91383056d71da85dae5e0db701e732916740c7079f32f8081a8c1db59c90486e"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "719f9926fbdd2663f975b14df4fa1137da6516e3e0e89a5c02cb7702aa242a1b"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff722d3745bd8370a9a9871f5568a51d47319285e267611ef14f229687e1b4d3"
      url "https://github.com/ryancswallace/jobman/releases/download/v#{version}/jobman_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jobman"
  desc "A daemon-less command line job manager with retries, timeouts, logging, notifications, and more."
  homepage "https://github.com/ryancswallace/jobman"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobman"
  manpage "docs/manpage/jobman.1"
  bash_completion "docs/completions/bash/jobman"
  zsh_completion "docs/completions/zsh/_jobman"

  # No zap stanza required

end
