title: Jobman Documentation
description: Documentation site for the Jobman CLI
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-sitemap

logo: "/assets/logo.png"
favicon_ico: "/assets/favicon.ico"

aux_links:
  "Jobman on GitHub":
    - "//github.com/ryancswallace/jobman"
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ryancswallace/jobman"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

footer_content: "Copyright &copy; Ryan Wallace. Distributed under an <a href=\"https://github.com/ryancswallace/jobman/tree/main/LICENSE\">MIT license.</a>"
last_edit_timestamp: false

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: light

collections:
  user_guide:
    permalink: "/:collection/:path/"
    output: true
  contributing:
    permalink: "/:collection/:path/"
    output: true
  other:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    user_guide:
      name: User Guide
      nav_exclude: false
      search_exclude: 
    contributing:
      name: Contributing
      nav_exclude: false
      search_exclude: false
    other:
      name: Other
      nav_exclude: false
      search_exclude: false
