---
name: Docs site

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/pages.yml"
      - "assets/**"
      - "CHANGELOG.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "Dockerfile.pages"
      - "Makefile"
      - "RELEASE.md"
      - "SECURITY.md"
      - "SUPPORT.md"
      - "devel/sitedocs/**"
      - "docs/**"
      - "etc/jobman/jobman.yml"
      - "go.mod"
      - "go.sum"
      - "go.version"
      - "jobman/**"
      - "site/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.version
          check-latest: true
          cache-dependency-path: go.sum

      - name: Stage documentation
        run: make gen-site

      - name: Set up Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # v1.0.13
        with:
          source: ./site-build
          destination: ./_site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./_site

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
