---
name: Test

on:
  push:
    branches: "*"

  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

  workflow_dispatch:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
